
spring.application.name=api-gateway
server.port=8080

spring.data.redis.host=localhost
spring.data.redis.port=6379

jwt.secret-key=${JWT_SECRET}

# =========================
# USER SERVICE
# =========================

# Auth Routes - No JWT required
spring.cloud.gateway.server.webflux.routes[0].id=user-service-auth
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/v1/auth/**


# User Service Routes - JWT Required
spring.cloud.gateway.server.webflux.routes[1].id=user-service
spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:8081
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/v1/users/**
spring.cloud.gateway.server.webflux.routes[1].filters[0]=JwtAuthFilter


# =========================
# POST SERVICE
# =========================

spring.cloud.gateway.server.webflux.routes[2].id=post-service
spring.cloud.gateway.server.webflux.routes[2].uri=http://localhost:8082
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/v1/posts/**
spring.cloud.gateway.server.webflux.routes[2].filters[0]=JwtAuthFilter


# =========================
# FEED SERVICE
# =========================

spring.cloud.gateway.server.webflux.routes[3].id=feed-service
spring.cloud.gateway.server.webflux.routes[3].uri=http://localhost:8083
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/v1/feed/**
spring.cloud.gateway.server.webflux.routes[3].filters[0]=JwtAuthFilter


# =========================
# SEARCH SERVICE
# =========================

spring.cloud.gateway.server.webflux.routes[4].id=search-service
spring.cloud.gateway.server.webflux.routes[4].uri=http://localhost:8084
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/api/v1/search/**
spring.cloud.gateway.server.webflux.routes[4].filters[0]=JwtAuthFilter

# =========================
# NOTIFICATION SERVICE
# =========================

spring.cloud.gateway.server.webflux.routes[5].id=notification-service
spring.cloud.gateway.server.webflux.routes[5].uri=http://localhost:8085
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/api/v1/notifications/**
spring.cloud.gateway.server.webflux.routes[5].filters[0]=JwtAuthFilter
