spring.application.name=search-service
server.port=8084

spring.elasticsearch.uris=${ELASTIC_URI}

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS}
spring.kafka.consumer.group-id=search-service-group
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

spring.kafka.consumer.properties.spring.json.trusted.packages=*

spring.kafka.consumer.properties.spring.json.type.mapping=\
com.sandeep.userservice.event.UserCreatedEvent:com.sandeep.searchservice.event.UserCreatedEvent,\
com.sandeep.userservice.event.UserUpdatedEvent:com.sandeep.searchservice.event.UserUpdatedEvent,\
com.sandeep.postservice.event.PostCreatedEvent:com.sandeep.searchservice.event.PostCreatedEvent