spring.application.name=feed-service
server.port=8083

spring.data.redis.host=localhost
spring.data.redis.port=6379


spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS}
spring.kafka.consumer.group-id=feed-service-group
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*

spring.kafka.consumer.properties.spring.json.type.mapping=\
com.sandeep.postservice.event.PostCreatedEvent:com.sandeep.feedservice.event.PostCreatedEvent,\
com.sandeep.postservice.event.PostDeletedEvent:com.sandeep.feedservice.event.PostDeletedEvent


user.service.url=${USER_SERVICE_URL}
feed.max-size=${FEED_SIZE}